// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// SPDX-FileCopyrightText: 2026 Bartosz Tomczyk <bartekplus@gmail.com>

//! Implementation-comment budget gate (`cargo xtask check-comment-density`).

use std::cmp::Ordering;
use std::path::{Path, PathBuf};

use anyhow::{Context as _, Result, bail};
use serde::Deserialize;

use crate::feature_status::display_path;
use crate::git_util::run_git;

const BUDGET_PATH: &str = "tools/comments/budget.toml";

#[derive(Debug, Deserialize)]
struct Budget {
    max_implementation_comment_lines: usize,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
struct CommentCounts {
    files: usize,
    generated_files: usize,
    implementation_comment_lines: usize,
    doc_comment_lines: usize,
    spdx_lines: usize,
}

/// Checks Rust source files against the implementation-comment budget.
pub(crate) fn check_comment_density(root: &Path) -> Result<()> {
    let budget_path = root.join(BUDGET_PATH);
    let budget_text = std::fs::read_to_string(&budget_path)
        .with_context(|| format!("failed to read {}", budget_path.display()))?;
    let budget: Budget = toml::from_str(&budget_text)
        .with_context(|| format!("failed to parse {}", budget_path.display()))?;

    let files = rust_source_files(root)?;
    let mut counts = CommentCounts::default();
    for path in files {
        let displayed = display_path(root, &path);
        let text = std::fs::read_to_string(&path)
            .with_context(|| format!("failed to read {displayed}"))?;
        counts.add_file(&text);
    }

    let message = enforce_budget(
        counts.implementation_comment_lines,
        budget.max_implementation_comment_lines,
    )?;
    eprintln!(
        "{message}; files={}, generated_files={}, doc_comment_lines={}, spdx_lines={}",
        counts.files, counts.generated_files, counts.doc_comment_lines, counts.spdx_lines
    );
    Ok(())
}

pub(crate) fn rust_source_files(root: &Path) -> Result<Vec<PathBuf>> {
    let output = run_git(
        root,
        &[
            "ls-files",
            "--cached",
            "--others",
            "--exclude-standard",
            "--",
            "crates",
            "xtask",
            "fuzz/fuzz_targets",
        ],
    )?;
    let mut files = output
        .lines()
        .filter(|line| {
            Path::new(line)
                .extension()
                .is_some_and(|ext| ext.eq_ignore_ascii_case("rs"))
        })
        .map(|line| root.join(line))
        .filter(|path| path.exists())
        .collect::<Vec<_>>();
    files.sort();
    files.dedup();
    Ok(files)
}

fn enforce_budget(actual: usize, ceiling: usize) -> Result<String> {
    match actual.cmp(&ceiling) {
        Ordering::Greater => {
            let over = actual - ceiling;
            bail!(
                "check-comment-density: {actual} implementation comment line(s) exceed the budget of {ceiling} (+{over} over)"
            );
        }
        Ordering::Less => {
            let under = ceiling - actual;
            Ok(format!(
                "check-comment-density: ok ({actual} implementation comment line(s), {under} under the {ceiling} budget). Ratchet down {BUDGET_PATH} to {actual}"
            ))
        }
        Ordering::Equal => Ok(format!(
            "check-comment-density: ok ({actual} implementation comment line(s), at budget)"
        )),
    }
}

impl CommentCounts {
    fn add_file(&mut self, text: &str) {
        self.files += 1;
        if is_generated_source(text) {
            self.generated_files += 1;
            return;
        }

        let file_counts = count_comment_lines(text);
        self.implementation_comment_lines += file_counts.implementation_comment_lines;
        self.doc_comment_lines += file_counts.doc_comment_lines;
        self.spdx_lines += file_counts.spdx_lines;
    }
}

pub(crate) fn is_generated_source(text: &str) -> bool {
    text.lines()
        .take(12)
        .any(|line| line.contains("@generated by `cargo xtask"))
}

fn count_comment_lines(text: &str) -> CommentCounts {
    let mut counts = CommentCounts::default();
    scan_comment_lines(text, |kind, _line_no, _line| match kind {
        CommentKind::Spdx => counts.spdx_lines += 1,
        CommentKind::Doc => counts.doc_comment_lines += 1,
        CommentKind::Implementation => counts.implementation_comment_lines += 1,
        CommentKind::TrailingImplementation => {}
    });
    counts
}

/// Classification of a single tracked-source comment line.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum CommentKind {
    /// An SPDX license-header line.
    Spdx,
    /// A Rustdoc line (`///`, `//!`, `/**`, `/*!`).
    Doc,
    /// A non-doc implementation comment line (`//`, `/*`).
    Implementation,
    /// A `//` comment trailing code on the same line. Excluded from the
    /// comment-density budget; still scanned for banned slop phrases.
    TrailingImplementation,
}

/// Visits every comment line in `text`, calling `on_comment` with the comment
/// kind, the 1-based source line number, and the trimmed line text.
///
/// String and raw-string contents are skipped, so a comment marker inside a
/// literal is not mistaken for a comment.
pub(crate) fn scan_comment_lines<'a>(
    text: &'a str,
    mut on_comment: impl FnMut(CommentKind, usize, &'a str),
) {
    let mut block = BlockComment::None;
    let mut string = StringState::None;

    for (idx, line) in text.lines().enumerate() {
        let line_no = idx + 1;
        let stripped = line.trim();
        if stripped.is_empty() {
            continue;
        }

        if string.is_active() {
            if let Some(at) = line_comment_start(stripped, &mut string) {
                on_comment(
                    CommentKind::TrailingImplementation,
                    line_no,
                    &stripped[at..],
                );
            }
            continue;
        }

        match block {
            BlockComment::Doc => {
                on_comment(CommentKind::Doc, line_no, stripped);
                if stripped.contains("*/") {
                    block = BlockComment::None;
                }
                continue;
            }
            BlockComment::Implementation => {
                on_comment(CommentKind::Implementation, line_no, stripped);
                if stripped.contains("*/") {
                    block = BlockComment::None;
                }
                continue;
            }
            BlockComment::None => {}
        }

        if stripped.starts_with("// SPDX-") {
            on_comment(CommentKind::Spdx, line_no, stripped);
        } else if stripped.starts_with("///") || stripped.starts_with("//!") {
            on_comment(CommentKind::Doc, line_no, stripped);
        } else if stripped.starts_with("/**") || stripped.starts_with("/*!") {
            on_comment(CommentKind::Doc, line_no, stripped);
            if !stripped.contains("*/") {
                block = BlockComment::Doc;
            }
        } else if stripped.starts_with("/*") {
            on_comment(CommentKind::Implementation, line_no, stripped);
            if !stripped.contains("*/") {
                block = BlockComment::Implementation;
            }
        } else if stripped.starts_with("//") {
            on_comment(CommentKind::Implementation, line_no, stripped);
        } else if let Some(at) = line_comment_start(stripped, &mut string) {
            on_comment(
                CommentKind::TrailingImplementation,
                line_no,
                &stripped[at..],
            );
        }
    }
}

fn line_comment_start(line: &str, state: &mut StringState) -> Option<usize> {
    let bytes = line.as_bytes();
    let mut escaped = false;
    let mut chars = line.char_indices().peekable();
    while let Some((idx, ch)) = chars.next() {
        match *state {
            StringState::None => {
                if ch == '/' && bytes.get(idx + 1) == Some(&b'/') {
                    return Some(idx);
                }
                if let Some((end, hashes)) = raw_string_start(line, idx) {
                    *state = StringState::Raw { hashes };
                    while chars.peek().is_some_and(|(next_idx, _)| *next_idx <= end) {
                        chars.next();
                    }
                } else if ch == '"' {
                    *state = StringState::Normal;
                } else if ch == '\''
                    && let Some(end) = char_literal_end(line, idx)
                {
                    while chars.peek().is_some_and(|(next_idx, _)| *next_idx <= end) {
                        chars.next();
                    }
                }
            }
            StringState::Normal => {
                if escaped {
                    escaped = false;
                    continue;
                }
                if ch == '\\' {
                    escaped = true;
                    continue;
                }
                if ch == '"' {
                    *state = StringState::None;
                }
            }
            StringState::Raw { hashes } => {
                if ch == '"' && raw_string_closes(line, idx, hashes) {
                    *state = StringState::None;
                }
            }
        }
    }
    None
}

fn raw_string_start(line: &str, start: usize) -> Option<(usize, usize)> {
    let bytes = line.as_bytes();
    if start > 0 {
        let prev = bytes[start - 1];
        if prev.is_ascii_alphanumeric() || prev == b'_' {
            return None;
        }
    }

    let mut idx = start;
    match bytes.get(idx).copied()? {
        b'r' => idx += 1,
        b'b' | b'c' => {
            idx += 1;
            if bytes.get(idx).copied()? != b'r' {
                return None;
            }
            idx += 1;
        }
        _ => return None,
    }

    let mut hashes = 0usize;
    while bytes.get(idx).is_some_and(|byte| *byte == b'#') {
        hashes += 1;
        idx += 1;
    }
    (bytes.get(idx).is_some_and(|byte| *byte == b'"')).then_some((idx, hashes))
}

fn raw_string_closes(line: &str, quote: usize, hashes: usize) -> bool {
    let bytes = line.as_bytes();
    let Some(tail) = bytes.get(quote + 1..quote + 1 + hashes) else {
        return false;
    };
    tail.iter().all(|byte| *byte == b'#')
}

fn char_literal_end(line: &str, start: usize) -> Option<usize> {
    let mut chars = line.get(start + 1..)?.char_indices();
    let (_, first) = chars.next()?;
    if first == '\'' {
        return None;
    }

    let content_end = if first == '\\' {
        let (escape_idx, escaped) = chars.next()?;
        match escaped {
            'x' => {
                let mut after_escape = start + 1 + escape_idx + escaped.len_utf8();
                for _ in 0..2 {
                    let hex = line.get(after_escape..)?.chars().next()?;
                    if !hex.is_ascii_hexdigit() {
                        return None;
                    }
                    after_escape += hex.len_utf8();
                }
                after_escape
            }
            'u' => {
                let mut after_escape = start + 1 + escape_idx + escaped.len_utf8();
                if !line.get(after_escape..)?.starts_with('{') {
                    return None;
                }
                after_escape += 1;
                after_escape += line.get(after_escape..)?.find('}')? + 1;
                after_escape
            }
            _ => start + 1 + escape_idx + escaped.len_utf8(),
        }
    } else {
        start + 1 + first.len_utf8()
    };

    line.get(content_end..)?
        .starts_with('\'')
        .then_some(content_end)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum BlockComment {
    None,
    Doc,
    Implementation,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum StringState {
    None,
    Normal,
    Raw { hashes: usize },
}

impl StringState {
    fn is_active(self) -> bool {
        !matches!(self, Self::None)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn enforce_ok(actual: usize, ceiling: usize) -> String {
        let result = enforce_budget(actual, ceiling);
        assert!(result.is_ok(), "expected budget check to pass: {result:?}");
        result.unwrap_or_default()
    }

    #[test]
    fn counts_implementation_comments_separately() {
        let counts = count_comment_lines(concat!(
            "// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0\n",
            "//! crate docs\n",
            "/// item docs\n",
            "// implementation\n",
            "/*\n",
            " * block implementation\n",
            " */\n",
            "const GENERATED_HEADER: &str = \"\\\n",
            "// string contents are not source comments\n",
            "\";\n",
            "fn main() {} // inline implementation comments are not part of the line budget\n",
        ));

        assert_eq!(counts.spdx_lines, 1);
        assert_eq!(counts.doc_comment_lines, 2);
        assert_eq!(counts.implementation_comment_lines, 4);
    }

    #[test]
    fn double_quote_char_literal_does_not_hide_following_comments() {
        let counts = count_comment_lines(concat!(
            "fn main() { let quote = '\"'; }\n",
            "// counted after the char literal\n",
        ));

        assert_eq!(counts.implementation_comment_lines, 1);
    }

    #[test]
    fn raw_string_quotes_do_not_hide_following_comments() {
        let counts = count_comment_lines(concat!(
            "const INLINE: &str = r#\"d(\"x\")\"#;\n",
            "const MULTI: &str = r##\"\n",
            "// raw string content is not a source comment\n",
            "\"##;\n",
            "// counted after raw strings\n",
        ));

        assert_eq!(counts.implementation_comment_lines, 1);
    }

    #[test]
    fn generated_sources_are_excluded() {
        let mut counts = CommentCounts::default();
        counts.add_file(concat!(
            "// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0\n",
            "// SPDX-FileCopyrightText: 2026 Bartosz Tomczyk <bartekplus@gmail.com>\n",
            "// @generated by `cargo xtask gen-tables` - DO NOT EDIT.\n",
            "// generated implementation marker\n",
        ));

        assert_eq!(counts.files, 1);
        assert_eq!(counts.generated_files, 1);
        assert_eq!(counts.implementation_comment_lines, 0);
        assert_eq!(counts.spdx_lines, 0);
    }

    #[test]
    fn over_budget_is_rejected() {
        let result = enforce_budget(11, 10);
        assert!(result.is_err());
        let msg = result.err().map(|err| err.to_string()).unwrap_or_default();
        assert!(msg.contains("exceed the budget of 10"), "{msg}");
        assert!(msg.contains("+1 over"), "{msg}");
    }

    #[test]
    fn at_budget_passes() {
        let msg = enforce_ok(10, 10);
        assert!(msg.contains("at budget"), "{msg}");
    }

    #[test]
    fn under_budget_passes_and_nudges_ratchet() {
        let msg = enforce_ok(7, 10);
        assert!(msg.contains("3 under"), "{msg}");
        assert!(msg.contains("Ratchet down"), "{msg}");
    }
}
