// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// SPDX-FileCopyrightText: 2026 Bartosz Tomczyk <bartekplus@gmail.com>

// @generated by `cargo xtask gen-tables` — DO NOT EDIT.
// Source: AV2 v1.0.0 § 9 additional tables, docs/spec/av2/1.0.0/attachments/all_tables.h
// (sha256 c3837e1c3b333e9ed51885c642562b519e3c3ed2ab385557d296c30a29c04ca1).
// Regenerate with `cargo xtask gen-tables`; the drift check runs in `cargo xtask ci`.

//! AV2 § 9 additional tables, generated by `cargo xtask gen-tables`.
//!
//! One submodule per § 9 subsection; see each module's docs for the
//! generating attachment and spec citation.

/// AV2 § 9.3 — Default CDF tables.
pub mod cdf;
/// AV2 § 9.2 — Conversion tables.
pub mod conversion;
/// AV2 § 9.8 — Loop restoration tables.
pub mod loop_restoration;
/// AV2 § 9.4 — Quantizer matrix tables.
pub mod quantizer;
/// AV2 § 9.7 — Secondary transform tables.
pub mod secondary_transform;
/// AV2 § 9.6 — 1D transform tables.
pub mod transform_1d;
/// AV2 § 9.5 — Warp filter tables.
pub mod warp_filter;
